batch_dir: "./input/"

#transcriber_backend: qwen
#language_identifier_backend: mms
#mms_lid_model_size: facebook/mms-lid-126

include:
  filename: ["*.wav", "*.mp3", "*.m4a"]
ignore: []
recursive: false
skip_existing: true
outdir: "./output/"
output:
  files: [txt]
  format:
    timestamp: minute
    speaker: change
    probability: line
    language: change
languages: [fr, en]
diarize: "pyannote"

profiles:
  # Stereo wav/mp3: split channels (host on one side), no diarization beyond per-channel labeling
  - include:
      filename: ["*.wav", "*.mp3"]
    # HOST on left channel, diarize on right
    diarize: "0=channel?speaker=HOST;pyannote"
  - include:
      filename: ["*.m4a"]
    # HOST on left channel, diarize on right
    diarize: "pyannote"
