name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
      - name: Check out the code (with tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ffmpeg portaudio19-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build sdist and wheel
        run: python -m build

      - name: Twine check
        run: python -m twine check dist/*

      - name: Smoke install built wheel
        run: |
          python -m venv .pkg-venv
          . .pkg-venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install dist/*.whl
          python -c "import verbatim; print('Imported verbatim', getattr(verbatim, '__version__', 'unknown'))"

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
